name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build an app
        run: |
          make build-app

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.goboolean.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push docker image to registry
        run: |
          docker tag fetch-system/worker:latest registry.goboolean.io/fetch-system/worker:${GITHUB_SHA::7}
          docker push registry.goboolean.io/fetch-system/worker:${GITHUB_SHA::7}

  kustomize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Extract image tag
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Update image tag
        uses: goboolean/manifests/.github/actions/update-image-tag@main
        with:
          app-name: ${{ github.event.repository.name }}
          image-tag: ${{ env.SHORT_SHA }}
          github-token: ${{ secrets.GOBOOLEAN_IO_TOKEN }}
          profile: dev
          pull-request-link: ${{ github.event.pull_request.html_url }}
